[package]
name = "wifi"
version = "0.1.0"
edition = "2024"

[dependencies]
neli-wifi = { version = "0.6.1" }
#tokio = { version = "1.48.0", features = ["full", "rt"] }
tui = "0.19"
crossterm = "0.29"
simple-logging = "2.0.2"
log = "0.4.29"
macaddr = "1.0.1"
chrono = "0.4.42"
directories = "6.0.0"
